### ISSUE TITLE
Embedded images?

### ISSUE THREAD

**Issue by MarcvdSluys** [novoid/github-orgmode-tests#11]
I was replacing [this README.md](https://github.com/hemel-waarnemen-com/Constellation-lines/blob/master/README.md) with a readme.org, when I realised that I don't know how to embed an image, like the CC BY 4.0 at the bottom of that page.  Do you know whether this is possible, and, if you do and it is, could you add an example?

**Comment by novoid** [comment]
I've used that at least in https://github.com/novoid/filetags

**Comment by novoid** [comment]
You can find an example in this repository's Readme.

**Comment by MarcvdSluys** [comment]
I realise I omitted the crucial part of my question - do you know how to embed a **remote** image in an ormode file on GitHub (e.g. a readme), i.e. using the full url like https://licensebuttons.net/l/by/3.0/88x31.png and show that image in the document...  I apologise for the fuss...

**Comment by novoid** [comment]
Yes, as I wrote above, it's in [the Readme of filetags](https://raw.githubusercontent.com/novoid/filetags/master/README.org) ;-)

**Comment by MarcvdSluys** [comment]
I don't know *what* I was looking with, but it wasn't my eyes...  Thanks so much for you patience :-)  While inserting an HTML block looks like a bit of a dirty trick, at least it does the job...  Thanks again!
