### ISSUE TITLE
Formatting inside link descriptions is broken

### ISSUE THREAD

**Issue by io12** [novoid/github-orgmode-tests#3]
For example, the following doesn't display correctly.

```org
[[https://gnu.org][~gnu~]]
```

The equivalent works for markdown, though.

**Comment by novoid** [comment]
It seems that you've found an error of an edge-case. You might want to report it to https://github.com/wallyqs/org-ruby ?

I added several syntax examples to various elements though. Thanks for your input!

**Comment by io12** [comment]
Reported upstream https://github.com/wallyqs/org-ruby/issues/85.
