### ISSUE TITLE
Any workarounds for drawers?

### ISSUE THREAD

**Issue by dangom** [novoid/github-orgmode-tests#6]
I'm writing notes using org-mode + emacs-jupyter via babel, but ob-jupyter wraps src block results into a :RESULTS: drawer. This cannot be deactivated, as it's part of the package's logic to identify and move point before/after results. 

The problem for me is that results don't render because github ignores drawers.

Do you guys happen to know any workarounds to have them show up? And how much work would it be to add drawer support?

**Comment by novoid** [comment]
Hi,

I'm not involved in developing the Ruby library that renders the Org mode syntax on GitHub. This is just a repo for my personal tests to see which elements are rendered how.

You could search&replace with a different block as a workaround.
