### ISSUE TITLE
Add #+MACRO replacement

### ISSUE THREAD

**Issue by yashi** [novoid/github-orgmode-tests#9]
It'd be nice to have a test for [macro replacement ](https://orgmode.org/org.html#Macro-Replacement).

**Comment by novoid** [comment]
@yashi I added it at the bottom. However, those kind of features are extremely unlikely to be interpreted by the usual rendering libraries.

**Comment by yashi** [comment]
@novoid Thanks. I know it won't get included. But it's nice to see that it's not actually supported.
